name: digimagz
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_screenutil: ^0.5.2
  cupertino_icons: ^0.1.2
  connectivity: 2.0.2
  dio: 3.0.10
  fluttertoast: 7.1.6
  shared_preferences: 0.5.12+4
  shimmer: 1.1.2
  cached_network_image: 2.0.0
  intl: 0.16.1
  flutter_svg: 0.19.0
  url_launcher: 5.7.10
  flutter_youtube: 2.0.0+1
  mcnmr_request_wrapper: 0.0.6
  mcnmr_common_ext:
  mcnmr_wrap_height_gridview:
  pull_to_refresh: 1.6.4
  provider: 4.0.0
  image_picker: 0.6.7+22
  share: 0.6.5+4
  path_provider: 1.6.27
  open_file: 3.0.3
  moor_flutter: 2.0.0
  firebase_auth: 0.14.0+5
  firebase_core: 0.4.0+9
  firebase_messaging: 6.0.13
  flutter_facebook_login:
  google_sign_in: 4.0.0
  webview_flutter: ^1.0.7
  flutter_local_notifications: 1.4.4+5
  overlay_support: 1.0.5
  flutter_html: ^0.11.1
  ext_storage: ^1.0.3

dev_dependencies:
  moor_generator: ^2.0.1
  build_runner:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher.png"



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/canvas.png
  - assets/images/logo.png
  - assets/images/logo_toolbar.png
  - assets/images/button_play.png
  - assets/images/ic_youtube.svg
  - assets/images/ic_facebook.svg
  - assets/images/ic_google.svg
  - assets/images/missing_avatar.jpg
  - assets/images/mqdefault.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
